apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-rest
  namespace: hello-rest
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: hello-rest
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hello-rest
    spec:
      containers:
        - name: api
          image: bittrance/hello-world:spring-undertow-hello-rest
          lifecycle:
            preStop:
              sleep:
                seconds: 2
          startupProbe:
            failureThreshold: 20
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: HELLO_REST_REQUEST_DELAY
              value: "0.2"
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-rest
spec:
  selector:
    app.kubernetes.io/name: hello-rest
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
      targetPort: http
